const WorkspacePreview = () => {
  return (
    <div className=" overflow-y-auto">
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
      <p>Pre view</p>
    </div>
  );
};
export default WorkspacePreview;
